apiVersion: v1
kind: Service
metadata:
  name: my-service-v1
spec:
  selector:
    app: my-service
    version: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-v2
spec:
  selector:
    app: my-service
    version: v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
