spring:
  main:
    banner-mode: off
  cloud:
    consul:
      discovery:
        enabled: true
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s

logging:
  config: "classpath:logback-spring.xml"
